# Generated by Django 4.2.1 on 2023-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default="CNBT", max_length=100),
        ),
    ]
