# Generated by Django 4.2.1 on 2023-05-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_student_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(default="CNBT", max_length=300),
        ),
    ]
